### ISSUE TITLE
Define reverse links to be automatically created

### ISSUE THREAD

**Issue by marcolarosa** [describo/profiles#8]
@beepsoft I'm thinking about putting this in for my app which is more around cultural collection management. It doesn't have to be in the crate-builder / profile layer (I could just do it in my app) but I think it could be generally useful. What do you think? Does the proposed implementation make sense?

---

To link one entity to another we define a forward looking relationship in the profile, viz:

`File : keywords -> DefinedTerm`

This gives us a link from the keywords prop on a File to a Defined Term.

However, when we look at the term, we don't have a  forward looking link from it back to the file, viz:

`DefinedTerm : appliesTo -> File`

We can get that association by looking at the @reverse links but that, semantically, doesn't mean as much as having a definite forward looking association.

So, it would be nice for a profile to be able to define a set of associations to be created automatically, ala:

```JS
{
  metadata: {},
  reverseMappings: [
    { property: 'keywords', reverse: 'appliesTo' },
    { property: 'memberOf', reverse: 'hasMember' },
    ...
  ],
  resolve: {},
  ...
}
``` 

Then, whenever an association is made from the `keywords` prop on any entity to another entity, the reverse will automatically be created by describo. That is, the target entity will get an `appliesTo` property linking back to the original entity.

When unlinking an entity from a property, if reverseMappings is defined, then both links should be removed.

If this configuration is not found in the profile then nothing happens.

**Comment by marcolarosa** [comment]
@beepsoft hi - have you seen this?

**Comment by beepsoft** [comment]
Sorry for the late answer. We don't use reverse links yet, but your proposal seems feasible. And it also seems backward compatible with the current profile format, so it is OK for us.

**Comment by marcolarosa** [comment]
Implemented but slightly changed API.

In order to be able to update the context automatically we also need pass in the property id.

```JS

 "propertyAssociations": [
        {
            "property": "keywords",
            "propertyId": "https://schema.org/keywords",
            "inverse": { "property": "isKeywordOf", "propertyId": "https://schema.org/isKeywordOf" }
        },
        {
            "property": "hasMember",
            "propertyId": "https://schema.org/hasMember",
            "inverse": {
                "property": "isMemberOf",
                "propertyId": "https://schema.org/isMemberOf"
            }
        }
    ],

```
